<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 DISTATIS | The R Opus v2</title>
  <meta name="description" content="<p>This bookdown is a complete update of Hildegarde Heymann’s “R Opus”
documentation, originally compiled in 2015. It gives helpful details and
walkthroughs on common multivariate analyses in <code>R</code> for sensory-evaluation data.</p>" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 DISTATIS | The R Opus v2" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/img/r-opus-cover.jpg" />
  <meta property="og:description" content="<p>This bookdown is a complete update of Hildegarde Heymann’s “R Opus”
documentation, originally compiled in 2015. It gives helpful details and
walkthroughs on common multivariate analyses in <code>R</code> for sensory-evaluation data.</p>" />
  <meta name="github-repo" content="jlahne/r-opus-v2" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 DISTATIS | The R Opus v2" />
  
  <meta name="twitter:description" content="<p>This bookdown is a complete update of Hildegarde Heymann’s “R Opus”
documentation, originally compiled in 2015. It gives helpful details and
walkthroughs on common multivariate analyses in <code>R</code> for sensory-evaluation data.</p>" />
  <meta name="twitter:image" content="/img/r-opus-cover.jpg" />

<meta name="author" content="Jacob Lahne" />


<meta name="date" content="2024-01-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multidimensional-scaling-mds.html"/>
<link rel="next" href="correspondence-analysis-ca.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The R Opus v2</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#usage"><i class="fa fa-check"></i>Usage</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-setup"><i class="fa fa-check"></i><code>R</code> Setup</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-this-is-not"><i class="fa fa-check"></i>What this is not</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-me"><i class="fa fa-check"></i>About me</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#session-info"><i class="fa fa-check"></i>Session Info</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html"><i class="fa fa-check"></i><b>1</b> Data import and set up</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#exploring-our-data"><i class="fa fa-check"></i><b>1.1</b> Exploring our data</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#the-descriptive-data"><i class="fa fa-check"></i><b>1.1.1</b> The descriptive data</a></li>
<li class="chapter" data-level="1.1.2" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#consumer-data"><i class="fa fa-check"></i><b>1.1.2</b> Consumer data</a></li>
<li class="chapter" data-level="1.1.3" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#the-other-data-frames"><i class="fa fa-check"></i><b>1.1.3</b> The other data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#wranglingtidying-data"><i class="fa fa-check"></i><b>1.2</b> Wrangling/tidying data</a></li>
<li class="chapter" data-level="1.3" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#wrap-up-and-summary"><i class="fa fa-check"></i><b>1.3</b> Wrap up and summary</a></li>
<li class="chapter" data-level="1.4" data-path="data-import-and-set-up.html"><a href="data-import-and-set-up.html#packages-used-in-this-chapter"><i class="fa fa-check"></i><b>1.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>2</b> Analysis of Variance</a>
<ul>
<li class="chapter" data-level="2.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#univariate-analysis-with-the-linear-model"><i class="fa fa-check"></i><b>2.1</b> Univariate analysis with the linear model</a></li>
<li class="chapter" data-level="2.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#pseudo-mixed-anova"><i class="fa fa-check"></i><b>2.2</b> Pseudo-mixed ANOVA</a></li>
<li class="chapter" data-level="2.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#mean-comparison-post-hoc-testing"><i class="fa fa-check"></i><b>2.3</b> Mean comparison (post-hoc testing)</a></li>
<li class="chapter" data-level="2.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#bonus-bayesian-approaches-to-anova"><i class="fa fa-check"></i><b>2.4</b> BONUS: Bayesian approaches to ANOVA</a></li>
<li class="chapter" data-level="2.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#packages-used-in-this-chapter-1"><i class="fa fa-check"></i><b>2.5</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dealing-with-missing-data.html"><a href="dealing-with-missing-data.html"><i class="fa fa-check"></i><b>3</b> Dealing with missing data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dealing-with-missing-data.html"><a href="dealing-with-missing-data.html#exploring-missing-data"><i class="fa fa-check"></i><b>3.1</b> Exploring missing data</a></li>
<li class="chapter" data-level="3.2" data-path="dealing-with-missing-data.html"><a href="dealing-with-missing-data.html#imputing-missing-data"><i class="fa fa-check"></i><b>3.2</b> Imputing missing data</a></li>
<li class="chapter" data-level="3.3" data-path="dealing-with-missing-data.html"><a href="dealing-with-missing-data.html#alternative-approaches-to-imputation"><i class="fa fa-check"></i><b>3.3</b> Alternative approaches to imputation</a></li>
<li class="chapter" data-level="3.4" data-path="dealing-with-missing-data.html"><a href="dealing-with-missing-data.html#packages-used-in-this-chapter-2"><i class="fa fa-check"></i><b>3.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="manova-multivariate-analysis-of-variance.html"><a href="manova-multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>4</b> MANOVA (Multivariate Analysis of Variance)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="manova-multivariate-analysis-of-variance.html"><a href="manova-multivariate-analysis-of-variance.html#running-manova"><i class="fa fa-check"></i><b>4.1</b> Running MANOVA</a></li>
<li class="chapter" data-level="4.2" data-path="manova-multivariate-analysis-of-variance.html"><a href="manova-multivariate-analysis-of-variance.html#what-does-manova-test"><i class="fa fa-check"></i><b>4.2</b> What does MANOVA test?</a></li>
<li class="chapter" data-level="4.3" data-path="manova-multivariate-analysis-of-variance.html"><a href="manova-multivariate-analysis-of-variance.html#bonus-hierarchical-bayes-instead-of-manova"><i class="fa fa-check"></i><b>4.3</b> BONUS: Hierarchical Bayes instead of MANOVA</a></li>
<li class="chapter" data-level="4.4" data-path="manova-multivariate-analysis-of-variance.html"><a href="manova-multivariate-analysis-of-variance.html#packages-used-in-this-chapter-3"><i class="fa fa-check"></i><b>4.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html"><i class="fa fa-check"></i><b>5</b> Canonical Variate Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html#what-is-cva"><i class="fa fa-check"></i><b>5.1</b> What is CVA?</a></li>
<li class="chapter" data-level="5.2" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html#application-of-cva"><i class="fa fa-check"></i><b>5.2</b> Application of CVA</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html#basic-visualization-of-cva"><i class="fa fa-check"></i><b>5.2.1</b> Basic visualization of CVA</a></li>
<li class="chapter" data-level="5.2.2" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html#an-aside-on-exporting-r-plots"><i class="fa fa-check"></i><b>5.2.2</b> An aside on exporting R plots</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html#plotting-uncertainty-in-cva"><i class="fa fa-check"></i><b>5.3</b> Plotting uncertainty in CVA</a></li>
<li class="chapter" data-level="5.4" data-path="canonical-variate-analysis.html"><a href="canonical-variate-analysis.html#packages-used-in-this-chapter-4"><i class="fa fa-check"></i><b>5.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html"><i class="fa fa-check"></i><b>6</b> Principal Components Analysis (PCA)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#what-does-pca-do"><i class="fa fa-check"></i><b>6.1</b> What does PCA do?</a></li>
<li class="chapter" data-level="6.2" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#lets-do-pca"><i class="fa fa-check"></i><b>6.2</b> Let’s do PCA!</a></li>
<li class="chapter" data-level="6.3" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#in-depth-interpretation"><i class="fa fa-check"></i><b>6.3</b> In-depth interpretation</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#correlations-or-squared-loadings-or-contributions"><i class="fa fa-check"></i><b>6.3.1</b> Correlations or (squared) loadings or contributions</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#pca-with-resampling-for-confidence-intervals"><i class="fa fa-check"></i><b>6.4</b> PCA with resampling for confidence intervals</a></li>
<li class="chapter" data-level="6.5" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#comparison-of-products-with-pca"><i class="fa fa-check"></i><b>6.5</b> Comparison of products with PCA</a></li>
<li class="chapter" data-level="6.6" data-path="principal-components-analysis-pca.html"><a href="principal-components-analysis-pca.html#packages-used-in-this-chapter-5"><i class="fa fa-check"></i><b>6.6</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="cluster-analysis.html"><a href="cluster-analysis.html"><i class="fa fa-check"></i><b>7</b> Cluster analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="cluster-analysis.html"><a href="cluster-analysis.html#hierarchical-clustering-on-distances"><i class="fa fa-check"></i><b>7.1</b> Hierarchical clustering on distances</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="cluster-analysis.html"><a href="cluster-analysis.html#wards-method"><i class="fa fa-check"></i><b>7.1.1</b> Ward’s Method</a></li>
<li class="chapter" data-level="7.1.2" data-path="cluster-analysis.html"><a href="cluster-analysis.html#single-linkage"><i class="fa fa-check"></i><b>7.1.2</b> Single linkage</a></li>
<li class="chapter" data-level="7.1.3" data-path="cluster-analysis.html"><a href="cluster-analysis.html#complete-linkage"><i class="fa fa-check"></i><b>7.1.3</b> Complete Linkage</a></li>
<li class="chapter" data-level="7.1.4" data-path="cluster-analysis.html"><a href="cluster-analysis.html#average-linkage"><i class="fa fa-check"></i><b>7.1.4</b> Average Linkage</a></li>
<li class="chapter" data-level="7.1.5" data-path="cluster-analysis.html"><a href="cluster-analysis.html#comparing-methods"><i class="fa fa-check"></i><b>7.1.5</b> Comparing methods</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="cluster-analysis.html"><a href="cluster-analysis.html#using-cluster-ids"><i class="fa fa-check"></i><b>7.2</b> Using cluster IDs</a></li>
<li class="chapter" data-level="7.3" data-path="cluster-analysis.html"><a href="cluster-analysis.html#k-means-clustering"><i class="fa fa-check"></i><b>7.3</b> K-means clustering</a></li>
<li class="chapter" data-level="7.4" data-path="cluster-analysis.html"><a href="cluster-analysis.html#packages-used-in-this-chapter-6"><i class="fa fa-check"></i><b>7.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html"><i class="fa fa-check"></i><b>8</b> Multidimensional Scaling (MDS)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#metric-vs-non-metric"><i class="fa fa-check"></i><b>8.1</b> Metric vs non-metric</a></li>
<li class="chapter" data-level="8.2" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#metric-mds"><i class="fa fa-check"></i><b>8.2</b> Metric MDS</a></li>
<li class="chapter" data-level="8.3" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#non-metric-mds"><i class="fa fa-check"></i><b>8.3</b> Non-metric MDS</a></li>
<li class="chapter" data-level="8.4" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#wrap-up"><i class="fa fa-check"></i><b>8.4</b> Wrap up</a></li>
<li class="chapter" data-level="8.5" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#packages-used-in-this-chapter-7"><i class="fa fa-check"></i><b>8.5</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distatis.html"><a href="distatis.html"><i class="fa fa-check"></i><b>9</b> DISTATIS</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distatis.html"><a href="distatis.html#the-dataset-sorting-wines-by-color"><i class="fa fa-check"></i><b>9.1</b> The dataset: sorting wines by color</a></li>
<li class="chapter" data-level="9.2" data-path="distatis.html"><a href="distatis.html#distatis-demonstrated"><i class="fa fa-check"></i><b>9.2</b> DISTATIS demonstrated</a></li>
<li class="chapter" data-level="9.3" data-path="distatis.html"><a href="distatis.html#comparison-to-mds"><i class="fa fa-check"></i><b>9.3</b> Comparison to MDS</a></li>
<li class="chapter" data-level="9.4" data-path="distatis.html"><a href="distatis.html#packages-used-in-this-chapter-8"><i class="fa fa-check"></i><b>9.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correspondence-analysis-ca.html"><a href="correspondence-analysis-ca.html"><i class="fa fa-check"></i><b>10</b> Correspondence Analysis (CA)</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correspondence-analysis-ca.html"><a href="correspondence-analysis-ca.html#packages-used-in-this-chapter-9"><i class="fa fa-check"></i><b>10.1</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="preference-mapping.html"><a href="preference-mapping.html"><i class="fa fa-check"></i><b>11</b> Preference Mapping</a>
<ul>
<li class="chapter" data-level="11.1" data-path="preference-mapping.html"><a href="preference-mapping.html#data"><i class="fa fa-check"></i><b>11.1</b> Data</a></li>
<li class="chapter" data-level="11.2" data-path="preference-mapping.html"><a href="preference-mapping.html#internal-preference-mapping"><i class="fa fa-check"></i><b>11.2</b> Internal preference mapping</a></li>
<li class="chapter" data-level="11.3" data-path="preference-mapping.html"><a href="preference-mapping.html#external-preference-mapping"><i class="fa fa-check"></i><b>11.3</b> External preference mapping</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="preference-mapping.html"><a href="preference-mapping.html#partial-least-squares-regression"><i class="fa fa-check"></i><b>11.3.1</b> Partial Least Squares Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="preference-mapping.html"><a href="preference-mapping.html#other-approaches"><i class="fa fa-check"></i><b>11.4</b> Other approaches</a></li>
<li class="chapter" data-level="11.5" data-path="preference-mapping.html"><a href="preference-mapping.html#principal-components-regression"><i class="fa fa-check"></i><b>11.5</b> Principal Components Regression</a></li>
<li class="chapter" data-level="11.6" data-path="preference-mapping.html"><a href="preference-mapping.html#packages-used-in-this-chapter-10"><i class="fa fa-check"></i><b>11.6</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="multiple-factorial-analysis-mfa.html"><a href="multiple-factorial-analysis-mfa.html"><i class="fa fa-check"></i><b>12</b> Multiple Factor(ial) Analysis (MFA)</a>
<ul>
<li class="chapter" data-level="12.1" data-path="multiple-factorial-analysis-mfa.html"><a href="multiple-factorial-analysis-mfa.html#mfa-vs-pca"><i class="fa fa-check"></i><b>12.1</b> MFA vs PCA</a></li>
<li class="chapter" data-level="12.2" data-path="multiple-factorial-analysis-mfa.html"><a href="multiple-factorial-analysis-mfa.html#mfa-with-different-measurements"><i class="fa fa-check"></i><b>12.2</b> MFA with different measurements</a></li>
<li class="chapter" data-level="12.3" data-path="multiple-factorial-analysis-mfa.html"><a href="multiple-factorial-analysis-mfa.html#wrapping-up"><i class="fa fa-check"></i><b>12.3</b> Wrapping up</a></li>
<li class="chapter" data-level="12.4" data-path="multiple-factorial-analysis-mfa.html"><a href="multiple-factorial-analysis-mfa.html#packages-used-in-this-chapter-11"><i class="fa fa-check"></i><b>12.4</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="generalized-procrustes-analysis.html"><a href="generalized-procrustes-analysis.html"><i class="fa fa-check"></i><b>13</b> Generalized Procrustes Analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="generalized-procrustes-analysis.html"><a href="generalized-procrustes-analysis.html#packages-used-in-this-chapter-12"><i class="fa fa-check"></i><b>13.1</b> Packages used in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="wrapping-up-1.html"><a href="wrapping-up-1.html"><i class="fa fa-check"></i><b>14</b> Wrapping up</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The R Opus v2</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="distatis" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> DISTATIS<a href="distatis.html#distatis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>DISTATIS is the “discriminant sorting” version of STATIS, which according to <span class="citation">H. Abdi et al. (<a href="#ref-abdiSTATIS2012">2012, 125</a>)</span> is a French acronym for</p>
<blockquote>
<p>“Structuration des Tableaux à Trois Indices de la Statistique” (which can, approximately, be translated as “structuring three way statistical tables”).</p>
</blockquote>
<p>Whereas STATIS is a methodology that is closely related to Multiple Factor Analysis <span class="citation">(MFA: <a href="#ref-abdiMultiple2013">Hervé Abdi, Williams, and Valentin 2013</a>)</span>, DISTATIS is a slght elaboration of the method primarily for analyzing the results of <strong>sorting tasks</strong>. In a sorting task, subjects receive a set of samples all at the same time (simultaneous sample presentation) and are asked to sort them into groups. Typically, subjects are not given specific criteria for sorting, although variations of the method do exist that specify this. Also typically, with <span class="math inline">\(n\)</span> samples, subjects are told to make between <span class="math inline">\(2\)</span> and <span class="math inline">\(n-1\)</span> groups (i.e., they cannot say all samples are identical or all samples are different). With this simple set of instructions, a set of 15-25 subjects can evaluate a set of samples in a relatively efficient fashion. The results are often not as well-defined or discriminating as traditional profiling methods (Descriptive Analysis, for the most part), but as a “first look” into the structure of a sample set, sorting tasks are often quite useful.</p>
<p>Two further points are worth mentioning:</p>
<ol style="list-style-type: decimal">
<li>DISTATIS can be used on any dissimilarity data, not just that from sorting tasks. It also does not require that the dissimilarity data be <em>binary</em> (as it is in a sorting task: in a group or not in a group). For example, DISTATIS can be used with the results of hierarchical or multiple sorting <span class="citation">(<a href="#ref-courcouxFree2023">Courcoux, Faye, and Qannari 2023</a>)</span>. Recently, “free linking” tasks, in which pairwise-similarity is judged among a set of samples (as opposed to group-wise similarity), have also been analyzed successfully with DISTATIS: these results are also non-binary similarities.</li>
<li>DISTATIS is closely related to MDS: it is an eigendecomposition on a set of dissimilarities. It differs primarily in data-preprocessing and in the generation of additional analytical outputs, which are often useful. The biplots produced by MDS and DISTATIS will usually be almost identical (see below).</li>
</ol>
<p>With that said, let’s launch into our application of DISTATIS.</p>
<div id="the-dataset-sorting-wines-by-color" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> The dataset: sorting wines by color<a href="distatis.html#the-dataset-sorting-wines-by-color" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’re actually going to use another dataset for this analysis, not the results of the DA we’ve been analyzing so far. We’re going to load the <code>sorting_r1</code> dataset, which according to HGH is</p>
<blockquote>
<p>color data that came from sorting the wines into similarly colored groups.</p>
</blockquote>
<p>Thus, the data pertain to the same wine, but is sorted into groups <em>by appearance</em> by 15 panelists.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="distatis.html#cb288-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb288-2"><a href="distatis.html#cb288-2" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb288-3"><a href="distatis.html#cb288-3" tabindex="-1"></a></span>
<span id="cb288-4"><a href="distatis.html#cb288-4" tabindex="-1"></a>sorting_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">&quot;data/sorting_r1.csv&quot;</span>))</span>
<span id="cb288-5"><a href="distatis.html#cb288-5" tabindex="-1"></a></span>
<span id="cb288-6"><a href="distatis.html#cb288-6" tabindex="-1"></a>sorting_data</span></code></pre></div>
<pre><code>## # A tibble: 8 × 16
##   wine      `263` `1331` `1400` `1401` `1402` `1404` `1405` `1408` `1409` `1412`
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
## 1 I_REFOSCO G6    G3     G5     G4     G5     G4     G2     G2     G1     G1    
## 2 I_MERLOT  G1    G3     G4     G3     G2     G3     G4     G3     G1     G2    
## 3 I_SYRAH   G5    G4     G2     G1     G1     G2     G1     G4     G1     G2    
## 4 I_PRIMIT… G2    G1     G3     G1     G4     G5     G3     G4     G3     G2    
## 5 C_SYRAH   G3    G2     G4     G4     G5     G6     G1     G3     G2     G4    
## 6 C_REFOSCO G4    G3     G1     G2     G5     G5     G2     G1     G2     G3    
## 7 C_MERLOT  G1    G2     G3     G3     G3     G1     G4     G3     G2     G2    
## 8 C_ZINFAN… G1    G5     G3     G3     G2     G1     G1     G3     G1     G2    
## # ℹ 5 more variables: `1413` &lt;chr&gt;, `1414` &lt;chr&gt;, `1415` &lt;chr&gt;, `1416` &lt;chr&gt;,
## #   `1417` &lt;chr&gt;</code></pre>
<p>It looks like the data are presented as follows: each row corresponds to 1 of the 8 wine samples we’ve been dealing with so far, and each column represents a panelist (coded numerically), with the cells showing which group they assigned the wine to. So, for example, panelist <code>263</code> assigned <code>I_REFOSCO</code> to group <code>G6</code>, whereas panelist <code>1331</code> assigned the same wine to group <code>G3</code>. You’ll notice, of course, that the problem with these data are that group numbers are dependent on panelist: it doesn’t matter what actual number is assigned, but rather <em>what other wines each panelist thinks are in the same group</em>. We need some way to show this data: this is exactly transforming groups into dissimilarities.</p>
<p>We are going to use the <code>DistatisR</code> package for much of the analysis in this section. It has a utility function, <code>DistanceFromSort()</code>, that will transform this kind of grouping information into dissimilarities: symmetrical matrices for each panelist that show dissimilarity. Let’s check it out:</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="distatis.html#cb290-1" tabindex="-1"></a><span class="fu">library</span>(DistatisR)</span>
<span id="cb290-2"><a href="distatis.html#cb290-2" tabindex="-1"></a></span>
<span id="cb290-3"><a href="distatis.html#cb290-3" tabindex="-1"></a>sorting_dissimilarities <span class="ot">&lt;-</span> </span>
<span id="cb290-4"><a href="distatis.html#cb290-4" tabindex="-1"></a>  sorting_data <span class="sc">%&gt;%</span></span>
<span id="cb290-5"><a href="distatis.html#cb290-5" tabindex="-1"></a>  <span class="co"># As is often the case, we need to move our ID column to `rownames`</span></span>
<span id="cb290-6"><a href="distatis.html#cb290-6" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">&quot;wine&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb290-7"><a href="distatis.html#cb290-7" tabindex="-1"></a>  <span class="fu">DistanceFromSort</span>()</span>
<span id="cb290-8"><a href="distatis.html#cb290-8" tabindex="-1"></a></span>
<span id="cb290-9"><a href="distatis.html#cb290-9" tabindex="-1"></a><span class="co"># Let&#39;s take a look at what we have now</span></span>
<span id="cb290-10"><a href="distatis.html#cb290-10" tabindex="-1"></a><span class="fu">str</span>(sorting_dissimilarities)</span></code></pre></div>
<pre><code>##  num [1:8, 1:8, 1:15] 0 1 1 1 1 1 1 1 1 0 ...
##  - attr(*, &quot;dimnames&quot;)=List of 3
##   ..$ : chr [1:8] &quot;I_REFOSCO&quot; &quot;I_MERLOT&quot; &quot;I_SYRAH&quot; &quot;I_PRIMITIVO&quot; ...
##   ..$ : chr [1:8] &quot;I_REFOSCO&quot; &quot;I_MERLOT&quot; &quot;I_SYRAH&quot; &quot;I_PRIMITIVO&quot; ...
##   ..$ : chr [1:15] &quot;263&quot; &quot;1331&quot; &quot;1400&quot; &quot;1401&quot; ...</code></pre>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="distatis.html#cb292-1" tabindex="-1"></a><span class="co"># And here is a &quot;slice&quot; of the sorting &quot;brick&quot; (3D array or tensor)</span></span>
<span id="cb292-2"><a href="distatis.html#cb292-2" tabindex="-1"></a>sorting_dissimilarities[, , <span class="dv">1</span>]</span></code></pre></div>
<pre><code>##             I_REFOSCO I_MERLOT I_SYRAH I_PRIMITIVO C_SYRAH C_REFOSCO C_MERLOT
## I_REFOSCO           0        1       1           1       1         1        1
## I_MERLOT            1        0       1           1       1         1        0
## I_SYRAH             1        1       0           1       1         1        1
## I_PRIMITIVO         1        1       1           0       1         1        1
## C_SYRAH             1        1       1           1       0         1        1
## C_REFOSCO           1        1       1           1       1         0        1
## C_MERLOT            1        0       1           1       1         1        0
## C_ZINFANDEL         1        0       1           1       1         1        0
##             C_ZINFANDEL
## I_REFOSCO             1
## I_MERLOT              0
## I_SYRAH               1
## I_PRIMITIVO           1
## C_SYRAH               1
## C_REFOSCO             1
## C_MERLOT              0
## C_ZINFANDEL           0</code></pre>
<p>In order to deal with these data, the <code>DistanceFromSort()</code> function produces a “brick” of data (more typically called an “array” or a “tensor” in the machine-learning literature). An array is a stack of matrices: the 3rd dimension, in this case, indexes subjects, so that <code>sorting_dissimilarities[, , 1]</code> gets the dissimilarity judgments of the first subject.</p>
<p>These matrices are symmetric and contain only <code>0</code> and <code>1</code>: <code>0</code> when the row and column wines are in the same group, and <code>1</code> when they are not. <span class="citation">H. Abdi et al. (<a href="#ref-abdiAnalyzing2007">2007</a>)</span> have a demonstration that this in fact constitutes a Euclidean distance.</p>
<p>For subject #1, it looks like most wines were different, with only one group of 2 wines being similar by color (<code>C_MERLOT</code> and <code>C_ZINFANDEL</code>).</p>
<p>You’ll notice that this process is much easier than the one used in the original <strong>R Opus</strong>. The <code>DistatisR</code> package has matured (it incorporates the code file that HGH references) and so much of the preprocessing is now fully automatic.</p>
</div>
<div id="distatis-demonstrated" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> DISTATIS demonstrated<a href="distatis.html#distatis-demonstrated" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I am not going to go into all of the steps of DISTATIS <span class="citation">(see instead <a href="#ref-abdiAnalyzing2007">H. Abdi et al. 2007</a>)</span>, but briefly: DISTATIS first uses multivariate statistics to evaluate how similar all the subjects’ sorts are to each other, then weights each subject by their similarity to the overall consensus, uses these weights to sum up the individual results into a consensus dissimilarity, and finally uses an eigendecomposition on the weighted sum to produce a map of (dis)similarities (this final step is the MDS-like part).</p>
<p>This multistep approach means that not only do we have the consensus results, but we have access to results that tell us how much consensus there actually is, as well as the ability to generate bootstrapped confidence intervals based on individuals.</p>
<p>Luckily, the <code>DistatisR</code> package makes it quite easy to run DISTATIS.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="distatis.html#cb294-1" tabindex="-1"></a>distatis_results <span class="ot">&lt;-</span> <span class="fu">distatis</span>(sorting_dissimilarities)</span>
<span id="cb294-2"><a href="distatis.html#cb294-2" tabindex="-1"></a></span>
<span id="cb294-3"><a href="distatis.html#cb294-3" tabindex="-1"></a><span class="co"># We will also generate some bootstrapped results while we&#39;re at it so as to be</span></span>
<span id="cb294-4"><a href="distatis.html#cb294-4" tabindex="-1"></a><span class="co"># able to plot confidence ellipses.</span></span>
<span id="cb294-5"><a href="distatis.html#cb294-5" tabindex="-1"></a>distatis_boots <span class="ot">&lt;-</span> <span class="fu">BootFromCompromise</span>(sorting_dissimilarities)</span></code></pre></div>
<pre><code>## [1] Starting Full Bootstrap. Iterations #: 
## [2] 1000</code></pre>
<p>Before we proceed, let’s look at what we’ve done:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="distatis.html#cb296-1" tabindex="-1"></a>distatis_results</span></code></pre></div>
<pre><code>## **Results for DiSTATIS**
## The analysis was performed on  15 individuals, on 8 sorted items.
## *The results are available in the following objects:
## 
##   name         description                                
## 1 &quot;$res4Cmat&quot;  &quot;Results from the C matrix (see notation)&quot; 
## 2 &quot;$res4Splus&quot; &quot;Results from the S+ matrix (see notation)&quot;
## 3 &quot;$compact&quot;   &quot;a boolean. TRUE if compact results used.&quot;</code></pre>
<p>You’ll notice that the output from <code>distatis()</code> is a complex list object that is reasonably well-annotated (similar to what can be found in the <code>FactoMineR</code> package outputs). We’ll dig into this in a minute.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="distatis.html#cb298-1" tabindex="-1"></a>distatis_boots <span class="sc">%&gt;%</span> str</span></code></pre></div>
<pre><code>##  num [1:8, 1:3, 1:1000] -0.2977 0.3056 -0.1425 -0.2006 0.0163 ...
##  - attr(*, &quot;dimnames&quot;)=List of 3
##   ..$ : chr [1:8] &quot;I_REFOSCO&quot; &quot;I_MERLOT&quot; &quot;I_SYRAH&quot; &quot;I_PRIMITIVO&quot; ...
##   ..$ : chr [1:3] &quot;Factor 1&quot; &quot;Factor 2&quot; &quot;Factor 3&quot;
##   ..$ : NULL</code></pre>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="distatis.html#cb300-1" tabindex="-1"></a>distatis_boots[, , <span class="dv">1</span>]</span></code></pre></div>
<pre><code>##                Factor 1     Factor 2    Factor 3
## I_REFOSCO   -0.29770527 -0.226722252  0.32144205
## I_MERLOT     0.30557584 -0.021761829  0.11218988
## I_SYRAH     -0.14252528  0.389636274 -0.11405814
## I_PRIMITIVO -0.20056334  0.383101360 -0.08491339
## C_SYRAH      0.01633474 -0.386653708 -0.17660434
## C_REFOSCO   -0.34770483 -0.220891918 -0.07295109
## C_MERLOT     0.31371989  0.003792725 -0.10295863
## C_ZINFANDEL  0.35286826  0.079499348  0.11785367</code></pre>
<p>The <code>BootFromCompromise()</code> function gives us another array: in this case a set of factor scores for the samples on the first 3 factors/components, over 1000 (the default) bootstrapped iterations. Each slice is a single bootstrapped iteration.</p>
<p>Finally, let’s examine our results. The output from <code>distatis()</code> stores results about the <em>samples</em> in the <code>$res4Splus</code> list, and results about the judges in the <code>$res4Cmat</code> list. These are named after the matrices defined in <span class="citation">H. Abdi et al. (<a href="#ref-abdiAnalyzing2007">2007</a>)</span>: the <span class="math inline">\(\mathbf{C}\)</span> matrix is the matrix of <span class="math inline">\(RV\)</span> coefficients between judges (a measure of multidimensional similarity), and the <span class="math inline">\(\mathbf{S_+}\)</span> matrix contains the compromise matrix of dissimilarities (after double-centering, weighting as I described above, and summing).</p>
<p>Let’s follow along in the order that HGH did in her workflow. She starts by examining first the overall explained variances. These are found in the <code>distatis_results$res4Splus$tau</code> vector.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="distatis.html#cb302-1" tabindex="-1"></a>distatis_results<span class="sc">$</span>res4Splus<span class="sc">$</span>tau <span class="sc">%&gt;%</span></span>
<span id="cb302-2"><a href="distatis.html#cb302-2" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;dim&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb302-3"><a href="distatis.html#cb302-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dim =</span> <span class="fu">str_c</span>(<span class="st">&quot;Dimension &quot;</span>, dim)) <span class="sc">%&gt;%</span></span>
<span id="cb302-4"><a href="distatis.html#cb302-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> dim, <span class="at">y =</span> value)) <span class="sc">+</span> </span>
<span id="cb302-5"><a href="distatis.html#cb302-5" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb302-6"><a href="distatis.html#cb302-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb302-7"><a href="distatis.html#cb302-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&quot;% variance explained&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>These results look the same as HGH’s (good news!), and we can see our first two dimensions explain about 41% of the total variation in the sorts; this is fairly common for sorting, in which getting very high explanation in 2 dimensions is unlikely.</p>
<p>Let’s look at how the products project into those first 2 dimensions.</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="distatis.html#cb304-1" tabindex="-1"></a>p_splus <span class="ot">&lt;-</span> </span>
<span id="cb304-2"><a href="distatis.html#cb304-2" tabindex="-1"></a>  distatis_results<span class="sc">$</span>res4Splus<span class="sc">$</span>F <span class="sc">%&gt;%</span></span>
<span id="cb304-3"><a href="distatis.html#cb304-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;sample&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb304-4"><a href="distatis.html#cb304-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Factor 1</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Factor 2</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb304-5"><a href="distatis.html#cb304-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span> </span>
<span id="cb304-6"><a href="distatis.html#cb304-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb304-7"><a href="distatis.html#cb304-7" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb304-8"><a href="distatis.html#cb304-8" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> sample)) <span class="sc">+</span></span>
<span id="cb304-9"><a href="distatis.html#cb304-9" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span> </span>
<span id="cb304-10"><a href="distatis.html#cb304-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb304-11"><a href="distatis.html#cb304-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">&quot;DISTATIS plot for compromise dissimilarities&quot;</span>)</span>
<span id="cb304-12"><a href="distatis.html#cb304-12" tabindex="-1"></a></span>
<span id="cb304-13"><a href="distatis.html#cb304-13" tabindex="-1"></a>p_splus</span></code></pre></div>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>These results are the same as HGH’s, again, which is good news.</p>
<p>HGH plotted the individual subjects as projected into this space. It’s a little annoying to do, and I do not think it is typically particularly illuminating, but we’ll do it here for practice.</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="distatis.html#cb305-1" tabindex="-1"></a>p_splus_augmented <span class="ot">&lt;-</span> p_splus</span>
<span id="cb305-2"><a href="distatis.html#cb305-2" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(distatis_results<span class="sc">$</span>res4Splus<span class="sc">$</span>PartialF)[<span class="dv">3</span>]){</span>
<span id="cb305-3"><a href="distatis.html#cb305-3" tabindex="-1"></a>  augmented_data <span class="ot">&lt;-</span> </span>
<span id="cb305-4"><a href="distatis.html#cb305-4" tabindex="-1"></a>    distatis_results<span class="sc">$</span>res4Splus<span class="sc">$</span>PartialF[, , i] <span class="sc">%&gt;%</span></span>
<span id="cb305-5"><a href="distatis.html#cb305-5" tabindex="-1"></a>    <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;sample&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb305-6"><a href="distatis.html#cb305-6" tabindex="-1"></a>    <span class="co"># and then add the compromise barycenters so we can draw lines to them</span></span>
<span id="cb305-7"><a href="distatis.html#cb305-7" tabindex="-1"></a>    <span class="fu">bind_cols</span>(</span>
<span id="cb305-8"><a href="distatis.html#cb305-8" tabindex="-1"></a>      distatis_results<span class="sc">$</span>res4Splus<span class="sc">$</span>F <span class="sc">%&gt;%</span></span>
<span id="cb305-9"><a href="distatis.html#cb305-9" tabindex="-1"></a>        <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb305-10"><a href="distatis.html#cb305-10" tabindex="-1"></a>        <span class="fu">rename</span>(<span class="at">xend =</span> <span class="dv">1</span>, <span class="at">yend =</span> <span class="dv">2</span>)</span>
<span id="cb305-11"><a href="distatis.html#cb305-11" tabindex="-1"></a>    )</span>
<span id="cb305-12"><a href="distatis.html#cb305-12" tabindex="-1"></a>  </span>
<span id="cb305-13"><a href="distatis.html#cb305-13" tabindex="-1"></a>  p_splus_augmented <span class="ot">&lt;-</span> </span>
<span id="cb305-14"><a href="distatis.html#cb305-14" tabindex="-1"></a>    p_splus_augmented <span class="sc">+</span></span>
<span id="cb305-15"><a href="distatis.html#cb305-15" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> augmented_data, </span>
<span id="cb305-16"><a href="distatis.html#cb305-16" tabindex="-1"></a>               <span class="at">shape =</span> <span class="dv">23</span>) <span class="sc">+</span> </span>
<span id="cb305-17"><a href="distatis.html#cb305-17" tabindex="-1"></a>    <span class="fu">geom_segment</span>(<span class="at">data =</span> augmented_data,</span>
<span id="cb305-18"><a href="distatis.html#cb305-18" tabindex="-1"></a>                 <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Factor 1</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Factor 2</span><span class="st">`</span>,</span>
<span id="cb305-19"><a href="distatis.html#cb305-19" tabindex="-1"></a>                     <span class="at">xend =</span> xend, <span class="at">yend =</span> yend),</span>
<span id="cb305-20"><a href="distatis.html#cb305-20" tabindex="-1"></a>                 <span class="at">size =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb305-21"><a href="distatis.html#cb305-21" tabindex="-1"></a>}</span>
<span id="cb305-22"><a href="distatis.html#cb305-22" tabindex="-1"></a></span>
<span id="cb305-23"><a href="distatis.html#cb305-23" tabindex="-1"></a>p_splus_augmented <span class="sc">+</span> </span>
<span id="cb305-24"><a href="distatis.html#cb305-24" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;DISTATIS compromise plot&quot;</span>,</span>
<span id="cb305-25"><a href="distatis.html#cb305-25" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Individual subjects are projected as hollow diamonds&quot;</span>)</span></code></pre></div>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>We can see how each wine’s position is actually the (weighted) barycenter of all the subject’s judgments about where that wine should be grouped. We could make this more easily readable by doing some work with colors and shapes, but I rarely find this kind of plot useful or informative. I leave this to the reader!</p>
<p>Before we move on to examining the subjects and comparing to MDS, let’s take a look at the bootstrapped confidence ellipses we generated.</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="distatis.html#cb306-1" tabindex="-1"></a><span class="co"># We will need to reshape these arrays into a tibble that we can more easily</span></span>
<span id="cb306-2"><a href="distatis.html#cb306-2" tabindex="-1"></a><span class="co"># feed into `stat_ellipse()`</span></span>
<span id="cb306-3"><a href="distatis.html#cb306-3" tabindex="-1"></a></span>
<span id="cb306-4"><a href="distatis.html#cb306-4" tabindex="-1"></a><span class="co"># I hate converting arrays to tibbles - if anyone has a better way than a loop,</span></span>
<span id="cb306-5"><a href="distatis.html#cb306-5" tabindex="-1"></a><span class="co"># let me know</span></span>
<span id="cb306-6"><a href="distatis.html#cb306-6" tabindex="-1"></a>boot_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>()</span>
<span id="cb306-7"><a href="distatis.html#cb306-7" tabindex="-1"></a></span>
<span id="cb306-8"><a href="distatis.html#cb306-8" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb306-9"><a href="distatis.html#cb306-9" tabindex="-1"></a>  boot_tbl <span class="ot">&lt;-</span> </span>
<span id="cb306-10"><a href="distatis.html#cb306-10" tabindex="-1"></a>    <span class="fu">bind_rows</span>(boot_tbl,</span>
<span id="cb306-11"><a href="distatis.html#cb306-11" tabindex="-1"></a>              distatis_boots[, , i] <span class="sc">%&gt;%</span></span>
<span id="cb306-12"><a href="distatis.html#cb306-12" tabindex="-1"></a>                <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;sample&quot;</span>))</span>
<span id="cb306-13"><a href="distatis.html#cb306-13" tabindex="-1"></a>}</span>
<span id="cb306-14"><a href="distatis.html#cb306-14" tabindex="-1"></a></span>
<span id="cb306-15"><a href="distatis.html#cb306-15" tabindex="-1"></a>p_splus_boots <span class="ot">&lt;-</span> </span>
<span id="cb306-16"><a href="distatis.html#cb306-16" tabindex="-1"></a>  distatis_results<span class="sc">$</span>res4Splus<span class="sc">$</span>F <span class="sc">%&gt;%</span></span>
<span id="cb306-17"><a href="distatis.html#cb306-17" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;sample&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb306-18"><a href="distatis.html#cb306-18" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Factor 1</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Factor 2</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb306-19"><a href="distatis.html#cb306-19" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span> </span>
<span id="cb306-20"><a href="distatis.html#cb306-20" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span></span>
<span id="cb306-21"><a href="distatis.html#cb306-21" tabindex="-1"></a>  <span class="fu">stat_ellipse</span>(<span class="at">data =</span> boot_tbl,</span>
<span id="cb306-22"><a href="distatis.html#cb306-22" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">fill =</span> sample), </span>
<span id="cb306-23"><a href="distatis.html#cb306-23" tabindex="-1"></a>               <span class="at">show.legend =</span> <span class="cn">FALSE</span>, </span>
<span id="cb306-24"><a href="distatis.html#cb306-24" tabindex="-1"></a>               <span class="at">geom =</span> <span class="st">&quot;polygon&quot;</span>,</span>
<span id="cb306-25"><a href="distatis.html#cb306-25" tabindex="-1"></a>               <span class="at">alpha =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb306-26"><a href="distatis.html#cb306-26" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> sample), <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb306-27"><a href="distatis.html#cb306-27" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> sample)) <span class="sc">+</span></span>
<span id="cb306-28"><a href="distatis.html#cb306-28" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span> </span>
<span id="cb306-29"><a href="distatis.html#cb306-29" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb306-30"><a href="distatis.html#cb306-30" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">&quot;DISTATIS compromise plot with bootstrapped ellipses&quot;</span>) <span class="sc">+</span></span>
<span id="cb306-31"><a href="distatis.html#cb306-31" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>() <span class="sc">+</span> </span>
<span id="cb306-32"><a href="distatis.html#cb306-32" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>()</span>
<span id="cb306-33"><a href="distatis.html#cb306-33" tabindex="-1"></a></span>
<span id="cb306-34"><a href="distatis.html#cb306-34" tabindex="-1"></a>p_splus_boots</span></code></pre></div>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>With bootstrapping, we can see that there are 4 distinct groups of samples that don’t appear to overlap even when we perturb the original data.</p>
<p>We can now turn our consideration to the subjects: how much did they agree? We use the <span class="math inline">\(RV\)</span> matrix to examine this.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="distatis.html#cb307-1" tabindex="-1"></a>distatis_results<span class="sc">$</span>res4Cmat<span class="sc">$</span>C <span class="sc">%&gt;%</span></span>
<span id="cb307-2"><a href="distatis.html#cb307-2" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##        263  1331  1400  1401  1402  1404  1405  1408  1409  1412  1413  1414
## 263  1.000 0.461 0.564 0.855 0.718 0.778 0.568 0.730 0.333 0.651 0.569 0.614
## 1331 0.461 1.000 0.452 0.333 0.476 0.533 0.511 0.464 0.419 0.322 0.214 0.710
## 1400 0.564 0.452 1.000 0.422 0.452 0.660 0.333 0.464 0.189 0.537 0.261 0.482
## 1401 0.855 0.333 0.422 1.000 0.711 0.627 0.399 0.730 0.181 0.639 0.371 0.438
## 1402 0.718 0.476 0.452 0.711 1.000 0.533 0.466 0.464 0.419 0.645 0.475 0.507
## 1404 0.778 0.533 0.660 0.627 0.533 1.000 0.462 0.581 0.324 0.487 0.493 0.622
## 1405 0.568 0.511 0.333 0.399 0.466 0.462 1.000 0.449 0.142 0.439 0.238 0.462
## 1408 0.730 0.464 0.464 0.730 0.464 0.581 0.449 1.000 0.219 0.432 0.237 0.581
## 1409 0.333 0.419 0.189 0.181 0.419 0.324 0.142 0.219 1.000 0.272 0.601 0.502
## 1412 0.651 0.322 0.537 0.639 0.645 0.487 0.439 0.432 0.272 1.000 0.495 0.372
## 1413 0.569 0.214 0.261 0.371 0.475 0.493 0.238 0.237 0.601 0.495 1.000 0.291
## 1414 0.614 0.710 0.482 0.438 0.507 0.622 0.462 0.581 0.502 0.372 0.291 1.000
## 1415 0.581 0.309 0.309 0.504 0.309 0.493 0.360 0.827 0.068 0.174 0.077 0.493
## 1416 0.377 0.289 0.533 0.254 0.311 0.438 0.212 0.341 0.318 0.238 0.238 0.462
## 1417 0.785 0.700 0.700 0.626 0.700 0.808 0.626 0.597 0.488 0.592 0.494 0.808
##       1415  1416  1417
## 263  0.581 0.377 0.785
## 1331 0.309 0.289 0.700
## 1400 0.309 0.533 0.700
## 1401 0.504 0.254 0.626
## 1402 0.309 0.311 0.700
## 1404 0.493 0.438 0.808
## 1405 0.360 0.212 0.626
## 1408 0.827 0.341 0.597
## 1409 0.068 0.318 0.488
## 1412 0.174 0.238 0.592
## 1413 0.077 0.238 0.494
## 1414 0.493 0.462 0.808
## 1415 1.000 0.216 0.378
## 1416 0.216 1.000 0.626
## 1417 0.378 0.626 1.000</code></pre>
<p><span class="math inline">\(RV\)</span> is a generalization of the concept of (Pearson) correlation to multivariate data. <span class="math inline">\(RV\)</span> coefficients between two matrices can only be positive, and is constrained to the <span class="math inline">\([0,1]\)</span> interval, with higher values indicating more agreement.</p>
<p>If we use eigendecomposition on the <span class="math inline">\(RV\)</span> matrix, the coordinates of each subject on the first dimension indicate their maximum agreement. We can use the first 2 dimensions to examine whether there are groups of subjects, as well as how well they agree in general:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="distatis.html#cb309-1" tabindex="-1"></a>p_cmat <span class="ot">&lt;-</span></span>
<span id="cb309-2"><a href="distatis.html#cb309-2" tabindex="-1"></a>  distatis_results<span class="sc">$</span>res4Cmat<span class="sc">$</span>G <span class="sc">%&gt;%</span></span>
<span id="cb309-3"><a href="distatis.html#cb309-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;subject&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb309-4"><a href="distatis.html#cb309-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">dim 1</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">dim 2</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb309-5"><a href="distatis.html#cb309-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span> </span>
<span id="cb309-6"><a href="distatis.html#cb309-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span> </span>
<span id="cb309-7"><a href="distatis.html#cb309-7" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb309-8"><a href="distatis.html#cb309-8" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> subject)) <span class="sc">+</span> </span>
<span id="cb309-9"><a href="distatis.html#cb309-9" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb309-10"><a href="distatis.html#cb309-10" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb309-11"><a href="distatis.html#cb309-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">&quot;DISTATIS subjects plot&quot;</span>)</span>
<span id="cb309-12"><a href="distatis.html#cb309-12" tabindex="-1"></a>  </span>
<span id="cb309-13"><a href="distatis.html#cb309-13" tabindex="-1"></a>p_cmat</span></code></pre></div>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Subjects’ positions on the x-axis here are proportional to the weight their sorts receive in the final consensus plot–we can see that overall subjects largely agree, with weights between just less than <code>0.5</code> up to about <code>0.85</code>. On the second dimension we do see a fair amount of spread, so it is obvious that there is some disagreement among subjects. However, without some grouping variable (like level of experience in winemaking), we can’t interpret whether this disagreement is systematic.</p>
</div>
<div id="comparison-to-mds" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Comparison to MDS<a href="distatis.html#comparison-to-mds" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>HGH goes on to also analyze these data via metric and non-metric MDS. We will use metric MDS for convenience. Because MDS requires a distance matrix, we have to convert our original sorting data into some kind of consensus. HGH used the <code>cluster::daisy()</code> function. Reading the <code>?daisy</code> file, it appears that this is a general dissimilarity tool. We’ll compare it to simply summing up the observed groups.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="distatis.html#cb310-1" tabindex="-1"></a>daisy_data <span class="ot">&lt;-</span> </span>
<span id="cb310-2"><a href="distatis.html#cb310-2" tabindex="-1"></a>  sorting_data <span class="sc">%&gt;%</span> </span>
<span id="cb310-3"><a href="distatis.html#cb310-3" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">&quot;wine&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb310-4"><a href="distatis.html#cb310-4" tabindex="-1"></a>  <span class="co"># `daisy()` does not seem to accept string data</span></span>
<span id="cb310-5"><a href="distatis.html#cb310-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">as.factor</span>(.))) <span class="sc">%&gt;%</span></span>
<span id="cb310-6"><a href="distatis.html#cb310-6" tabindex="-1"></a>  cluster<span class="sc">::</span><span class="fu">daisy</span>()</span>
<span id="cb310-7"><a href="distatis.html#cb310-7" tabindex="-1"></a></span>
<span id="cb310-8"><a href="distatis.html#cb310-8" tabindex="-1"></a>simple_data <span class="ot">&lt;-</span> </span>
<span id="cb310-9"><a href="distatis.html#cb310-9" tabindex="-1"></a>  sorting_data <span class="sc">%&gt;%</span></span>
<span id="cb310-10"><a href="distatis.html#cb310-10" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">&quot;wine&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb310-11"><a href="distatis.html#cb310-11" tabindex="-1"></a>  <span class="fu">DistanceFromSort</span>() <span class="sc">%&gt;%</span></span>
<span id="cb310-12"><a href="distatis.html#cb310-12" tabindex="-1"></a>  <span class="co"># Here we summ across the 3rd dimension of the array, &quot;squishing&quot; it </span></span>
<span id="cb310-13"><a href="distatis.html#cb310-13" tabindex="-1"></a>  <span class="fu">apply</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), sum) <span class="sc">%&gt;%</span></span>
<span id="cb310-14"><a href="distatis.html#cb310-14" tabindex="-1"></a>  <span class="fu">dist</span>(<span class="at">method =</span> <span class="st">&quot;max&quot;</span>)</span>
<span id="cb310-15"><a href="distatis.html#cb310-15" tabindex="-1"></a></span>
<span id="cb310-16"><a href="distatis.html#cb310-16" tabindex="-1"></a>p_mds_daisy <span class="ot">&lt;-</span> </span>
<span id="cb310-17"><a href="distatis.html#cb310-17" tabindex="-1"></a>  daisy_data <span class="sc">%&gt;%</span></span>
<span id="cb310-18"><a href="distatis.html#cb310-18" tabindex="-1"></a>  <span class="fu">cmdscale</span>() <span class="sc">%&gt;%</span></span>
<span id="cb310-19"><a href="distatis.html#cb310-19" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;wine&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb310-20"><a href="distatis.html#cb310-20" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> V1, <span class="at">y =</span> V2)) <span class="sc">+</span> </span>
<span id="cb310-21"><a href="distatis.html#cb310-21" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb310-22"><a href="distatis.html#cb310-22" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> wine)) <span class="sc">+</span> </span>
<span id="cb310-23"><a href="distatis.html#cb310-23" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span> </span>
<span id="cb310-24"><a href="distatis.html#cb310-24" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Dimension 1&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Dimension 2&quot;</span>,</span>
<span id="cb310-25"><a href="distatis.html#cb310-25" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;MDS with dissimilarities derived from Gower&#39;s distance&quot;</span>) <span class="sc">+</span> </span>
<span id="cb310-26"><a href="distatis.html#cb310-26" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb310-27"><a href="distatis.html#cb310-27" tabindex="-1"></a></span>
<span id="cb310-28"><a href="distatis.html#cb310-28" tabindex="-1"></a>p_mds_simple <span class="ot">&lt;-</span> </span>
<span id="cb310-29"><a href="distatis.html#cb310-29" tabindex="-1"></a>  simple_data <span class="sc">%&gt;%</span></span>
<span id="cb310-30"><a href="distatis.html#cb310-30" tabindex="-1"></a>  <span class="fu">cmdscale</span>() <span class="sc">%&gt;%</span></span>
<span id="cb310-31"><a href="distatis.html#cb310-31" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;wine&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb310-32"><a href="distatis.html#cb310-32" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> V1, <span class="at">y =</span> V2)) <span class="sc">+</span> </span>
<span id="cb310-33"><a href="distatis.html#cb310-33" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb310-34"><a href="distatis.html#cb310-34" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> wine)) <span class="sc">+</span> </span>
<span id="cb310-35"><a href="distatis.html#cb310-35" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span> </span>
<span id="cb310-36"><a href="distatis.html#cb310-36" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Dimension 1&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Dimension 2&quot;</span>,</span>
<span id="cb310-37"><a href="distatis.html#cb310-37" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;MDS with dissimilarities from simply summing sorts&quot;</span>) <span class="sc">+</span> </span>
<span id="cb310-38"><a href="distatis.html#cb310-38" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb310-39"><a href="distatis.html#cb310-39" tabindex="-1"></a></span>
<span id="cb310-40"><a href="distatis.html#cb310-40" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb310-41"><a href="distatis.html#cb310-41" tabindex="-1"></a></span>
<span id="cb310-42"><a href="distatis.html#cb310-42" tabindex="-1"></a>p_mds_simple <span class="sc">+</span> p_mds_daisy</span></code></pre></div>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-12-1.png" width="768" /></p>
<p>We can see that the dissimilarities produced from <code>daisy()</code> and from our simple sum of dissimilarities are the same except for a scale constant.</p>
<p>Finally, we can compare this alignment to that from DISTATIS:</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="distatis.html#cb311-1" tabindex="-1"></a>p_splus <span class="sc">+</span> p_mds_simple</span></code></pre></div>
<p><img src="09-DISTATIS_files/figure-html/unnamed-chunk-13-1.png" width="768" /></p>
<p>We can see that overall our results are extremely similar, although there are some changes (the incerased spread between the Merlot wines in the DISTATIS plot, and the decreased spread between the Refosco wines).</p>
</div>
<div id="packages-used-in-this-chapter-8" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Packages used in this chapter<a href="distatis.html#packages-used-in-this-chapter-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="distatis.html#cb312-1" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div>
<pre><code>## R version 4.3.1 (2023-06-16)
## Platform: aarch64-apple-darwin20 (64-bit)
## Running under: macOS Ventura 13.6.1
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
## LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## time zone: America/New_York
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] patchwork_1.1.2 DistatisR_1.1.1 here_1.0.1      lubridate_1.9.2
##  [5] forcats_1.0.0   stringr_1.5.0   dplyr_1.1.2     purrr_1.0.1    
##  [9] readr_2.1.4     tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.3  
## [13] tidyverse_2.0.0
## 
## loaded via a namespace (and not attached):
##  [1] gtable_0.3.4       xfun_0.39          bslib_0.5.1        ggrepel_0.9.3     
##  [5] lattice_0.21-8     tzdb_0.4.0         vctrs_0.6.3        tools_4.3.1       
##  [9] generics_0.1.3     parallel_4.3.1     fansi_1.0.4        cluster_2.1.4     
## [13] highr_0.10         janeaustenr_1.0.0  pkgconfig_2.0.3    prettyGraphs_2.1.6
## [17] tokenizers_0.3.0   Matrix_1.6-0       readxl_1.4.3       lifecycle_1.0.3   
## [21] compiler_4.3.1     farver_2.1.1       munsell_0.5.0      carData_3.0-5     
## [25] htmltools_0.5.6    SnowballC_0.7.1    sass_0.4.7         yaml_2.3.7        
## [29] tidytext_0.4.1     pillar_1.9.0       car_3.1-2          crayon_1.5.2      
## [33] jquerylib_0.1.4    MASS_7.3-60        cachem_1.0.8       abind_1.4-5       
## [37] tidyselect_1.2.0   digest_0.6.33      stringi_1.7.12     bookdown_0.37     
## [41] labeling_0.4.3     rprojroot_2.0.3    fastmap_1.1.1      grid_4.3.1        
## [45] colorspace_2.1-0   cli_3.6.1          magrittr_2.0.3     utf8_1.2.3        
## [49] withr_2.5.0        scales_1.2.1       bit64_4.0.5        timechange_0.2.0  
## [53] rmarkdown_2.23     bit_4.0.5          cellranger_1.1.0   hms_1.1.3         
## [57] evaluate_0.21      knitr_1.43         viridisLite_0.4.2  rlang_1.1.1       
## [61] Rcpp_1.0.11        glue_1.6.2         rstudioapi_0.15.0  vroom_1.6.3       
## [65] jsonlite_1.8.7     R6_2.5.1</code></pre>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-abdiMultiple2013" class="csl-entry">
Abdi, Hervé, Lynne J. Williams, and Domininique Valentin. 2013. <span>“Multiple Factor Analysis: Principal Component Analysis for Multitable and Multiblock Data Sets: <span>Multiple</span> Factor Analysis.”</span> <em>Wiley Interdisciplinary Reviews: Computational Statistics</em> 5 (2): 149–79. <a href="https://doi.org/10.1002/wics.1246">https://doi.org/10.1002/wics.1246</a>.
</div>
<div id="ref-abdiAnalyzing2007" class="csl-entry">
Abdi, H., D. Valentin, S. Chollet, and C. Chrea. 2007. <span>“Analyzing Assessors and Products in Sorting Tasks: <span>DISTATIS</span>, Theory and Applications.”</span> <em>Food Quality and Preference</em> 18 (4): 627–40. <a href="https://doi.org/10.1016/j.foodqual.2006.09.003">https://doi.org/10.1016/j.foodqual.2006.09.003</a>.
</div>
<div id="ref-abdiSTATIS2012" class="csl-entry">
Abdi, H., L. J. Williams, D. Valentin, and M. Bennani-Dosse. 2012. <span>“<span>STATIS</span> and <span>DISTATIS</span>: Optimum Multitable Principal Component Analysis and Three Way Metric Multidimensional Scaling: <span>STATIS</span> and <span>DISTATIS</span>.”</span> <em>Wiley Interdisciplinary Reviews: Computational Statistics</em> 4 (2): 124–67. <a href="https://doi.org/10.1002/wics.198">https://doi.org/10.1002/wics.198</a>.
</div>
<div id="ref-courcouxFree2023" class="csl-entry">
Courcoux, P., P. Faye, and E. M. Qannari. 2023. <span>“Free Sorting as a Sensory Profiling Technique for Product Development.”</span> In <em>Rapid <span>Sensory Profiling Techniques</span></em>, edited by J. Delarue and J. Benjamin Lawlor, 2nd ed. <span>Woodhead</span>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multidimensional-scaling-mds.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="correspondence-analysis-ca.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/09-DISTATIS.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
